// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "Listar cursos",
  description: "Lista cursos do Nexus com filtros opcionais por unidade (sp/bsb), tipo (modular/pos_graduacao) e busca por nome/mnem\xF4nico.",
  inputSchema: {
    unit: z.enum(["sp", "bsb"]).optional().describe("Unidade: sp ou bsb"),
    type: z.enum(["modular", "pos_graduacao"]).optional().describe("Tipo de curso"),
    search: z.string().optional().describe("Termo para buscar em nome ou mnem\xF4nico"),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de resultados (padr\xE3o 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unit, type, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = sb(ctx).from("courses").select("id, name, mnemonic, unit, type, modality, workload_hours, price").order("name").limit(limit ?? 50);
    if (unit) q = q.eq("unit", unit);
    if (type) q = q.eq("type", type);
    if (search) q = q.or(`name.ilike.%${search}%,mnemonic.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_course_default = defineTool2({
  name: "get_course",
  title: "Detalhes do curso",
  description: "Retorna informa\xE7\xF5es completas de um curso (por id OU mnem\xF4nico + unidade), incluindo m\xF3dulos e pr\xF3ximas turmas.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("ID do curso"),
    mnemonic: z2.string().optional().describe("Mnem\xF4nico (ex.: CM US MORF)"),
    unit: z2.enum(["sp", "bsb"]).optional().describe("Unidade \u2014 obrigat\xF3ria quando usar mnem\xF4nico")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, mnemonic, unit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb2(ctx);
    let courseQ = client.from("courses").select("*").limit(1);
    if (id) courseQ = courseQ.eq("id", id);
    else if (mnemonic && unit) courseQ = courseQ.eq("mnemonic", mnemonic).eq("unit", unit);
    else
      return {
        content: [{ type: "text", text: "Informe id OU (mnemonic + unit)" }],
        isError: true
      };
    const { data: courseRows, error } = await courseQ;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const course = courseRows?.[0];
    if (!course) return { content: [{ type: "text", text: "Curso n\xE3o encontrado" }], isError: true };
    const [{ data: modules }, { data: links }] = await Promise.all([
      client.from("course_modules").select("title, description, position").eq("course_id", course.id).order("position"),
      client.from("class_group_courses").select("class_group:class_groups(id, start_date, end_date, status, unit, location)").eq("course_id", course.id)
    ]);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const upcoming = (links ?? []).map((l) => l.class_group).filter((g) => g && g.start_date >= today).sort((a, b) => a.start_date.localeCompare(b.start_date));
    const payload = { course, modules: modules ?? [], upcoming_class_groups: upcoming };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-upcoming-classes.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_classes_default = defineTool3({
  name: "list_upcoming_classes",
  title: "Pr\xF3ximas turmas",
  description: "Lista as pr\xF3ximas turmas (class_groups) com filtro opcional por unidade e janela em dias.",
  inputSchema: {
    unit: z3.enum(["sp", "bsb"]).optional().describe("Unidade: sp ou bsb"),
    days_ahead: z3.number().int().min(1).max(365).optional().describe("Janela em dias a partir de hoje (padr\xE3o 90)"),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unit, days_ahead, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const today = /* @__PURE__ */ new Date();
    const until = new Date(today.getTime() + (days_ahead ?? 90) * 864e5);
    let q = sb3(ctx).from("class_groups").select("id, start_date, end_date, status, unit, location, class_group_courses(course:courses(id, name, mnemonic))").gte("start_date", today.toISOString().slice(0, 10)).lte("start_date", until.toISOString().slice(0, 10)).order("start_date").limit(limit ?? 100);
    if (unit) q = q.eq("unit", unit);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { class_groups: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gstetvmsgjsbgilharjb";
var mcp_default = defineMcp({
  name: "nexus-hub-mcp",
  title: "Nexus Ultrassonografia \u2014 Hub",
  version: "0.1.0",
  instructions: "Ferramentas do hub interno Nexus: consultar cursos (modulares e p\xF3s), m\xF3dulos, turmas e agenda em SP e Bras\xEDlia. Todas as chamadas respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, get_course_default, list_upcoming_classes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
